# Generated by Django 3.1.1 on 2020-09-29 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(max_length=200)),
                ('year', models.IntegerField(choices=[('1960', '1960'), ('1970', '1970'), ('1980', '1980'), ('1990', '1990')], null=True)),
                ('image_type', models.CharField(choices=[('Breaker', 'breaker'), ('Sheet', 'sheet')], max_length=8, null=True)),
                ('is_complete', models.BooleanField(null=True)),
                ('date_complete', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[('1960', '1960'), ('1970', '1970'), ('1980', '1980'), ('1990', '1990')], null=True)),
                ('form_type', models.CharField(choices=[('short', 'Short'), ('long', 'Long')], max_length=200)),
                ('breaker_id', models.CharField(max_length=200)),
                ('img_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntryApp.image')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, null=True)),
                ('middle_init', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('sex', models.BooleanField(choices=[(0, 'Male'), (1, 'Female')], null=True)),
                ('race', models.CharField(max_length=50, null=True)),
                ('page_no', models.PositiveIntegerField(null=True)),
                ('line_no', models.PositiveIntegerField(null=True)),
                ('serial_no', models.IntegerField(null=True)),
                ('block', models.CharField(max_length=50, null=True)),
                ('sample_key_gq', models.CharField(max_length=50, null=True)),
                ('relp', models.CharField(max_length=50, null=True)),
                ('ind', models.CharField(max_length=50, null=True)),
                ('occp', models.CharField(max_length=50, null=True)),
                ('birth_year', models.PositiveIntegerField(null=True)),
                ('birth_month', models.CharField(max_length=15, null=True)),
                ('total_persons', models.PositiveIntegerField(null=True)),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('entry_time', models.DateTimeField()),
                ('is_illegible', models.BooleanField(blank=True, null=True)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntryApp.sheet')),
            ],
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('conflict_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('conflict_fields', models.TextField()),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntryApp.record')),
            ],
        ),
        migrations.CreateModel(
            name='Breaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[('1960', '1960'), ('1970', '1970'), ('1980', '1980'), ('1990', '1990')], null=True)),
                ('state', models.CharField(max_length=2, null=True)),
                ('county', models.CharField(max_length=30, null=True)),
                ('enum_dist', models.CharField(max_length=30, null=True)),
                ('mcd', models.CharField(max_length=30, null=True)),
                ('tract', models.CharField(max_length=30, null=True)),
                ('place', models.CharField(max_length=30, null=True)),
                ('smsa', models.CharField(max_length=30, null=True)),
                ('large_do_ed', models.CharField(max_length=30, null=True)),
                ('img_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntryApp.image')),
            ],
        ),
    ]
