# Generated by Django 3.1.1 on 2020-09-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('is_complete', models.BooleanField()),
                ('date_complete', models.DateTimeField()),
                ('state', models.CharField(max_length=2)),
                ('county', models.CharField(max_length=30)),
                ('enum_dist', models.CharField(max_length=30)),
                ('mcd', models.CharField(max_length=30)),
                ('tract', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('smsa', models.CharField(max_length=30)),
                ('large_do_ed', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('is_complete', models.BooleanField()),
                ('date_complete', models.DateTimeField()),
                ('form_type', models.CharField(max_length=200)),
                ('breaker_id', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_init', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.BooleanField(choices=[(0, 'Male'), (1, 'Female')])),
                ('race', models.CharField(max_length=50)),
                ('page_no', models.PositiveIntegerField()),
                ('line_no', models.PositiveIntegerField()),
                ('serial_no', models.IntegerField()),
                ('block', models.CharField(max_length=50)),
                ('sample_key_gq', models.CharField(max_length=50)),
                ('relp', models.CharField(max_length=50)),
                ('ind', models.CharField(max_length=50)),
                ('occp', models.CharField(max_length=50)),
                ('birth_year', models.PositiveIntegerField()),
                ('birth_month', models.CharField(max_length=15)),
                ('total_persons', models.PositiveIntegerField()),
                ('user_id', models.CharField(max_length=50)),
                ('entry_time', models.DateTimeField()),
                ('is_illegible', models.BooleanField()),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntryApp.sheet')),
            ],
        ),
    ]
