# Generated by Django 3.1.4 on 2021-04-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaker',
            name='jbid',
            field=models.CharField(default='jbid000', max_length=20),
        ),
        migrations.AlterField(
            model_name='otherimage',
            name='jbid',
            field=models.CharField(default='jbid000', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='jbid',
            field=models.CharField(default='jbid000', max_length=20),
        ),
        migrations.AlterField(
            model_name='sheet',
            name='jbid',
            field=models.CharField(default='jbid000', max_length=20),
        ),
    ]
