# Generated by Django 3.1.1 on 2020-09-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EntryApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('conflict_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('conflict_fields', models.TextField()),
                ('record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntryApp.record')),
            ],
        ),
    ]
