# Generated by Django 3.1.1 on 2020-10-15 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EntryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currententry',
            name='sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EntryApp.sheet'),
        ),
    ]
