# Generated by Django 3.1.4 on 2021-04-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryApp', '0002_auto_20210402_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breaker',
            name='county',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breaker',
            name='enumeration_district',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breaker',
            name='mcd',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breaker',
            name='place',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breaker',
            name='smsa',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breaker',
            name='state',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breaker',
            name='tract',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='flagged_view',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='age_hundreds',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='age_ones',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='age_tens',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='birth_decade',
            field=models.CharField(choices=[('1850', '185-'), ('1860', '186-'), ('1870', '187-'), ('1880', '188-'), ('1890', '189-'), ('1900', '190-'), ('1910', '191-'), ('1920', '192-'), ('1930', '193-'), ('1940', '194-'), ('1950', '195-'), ('1960', '196-')], default=('1850', '185-'), max_length=255, null=True, verbose_name='Decade of birth'),
        ),
        migrations.AlterField(
            model_name='record',
            name='birth_quarter',
            field=models.CharField(choices=[('Jan-Mar', 'Jan-Mar'), ('Apr-June', 'Apr-June'), ('July-Sept', 'July-Sept'), ('Oct-Dec', 'Jan-Mar')], default=('Jan-Mar', 'Jan-Mar'), max_length=255, null=True, verbose_name='Month of birth'),
        ),
        migrations.AlterField(
            model_name='record',
            name='birth_year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name='Specific year of birth'),
        ),
        migrations.AlterField(
            model_name='record',
            name='birth_year_hundreds',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='birth_year_ones',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='birth_year_tens',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='birth_year_thousands',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='block_1',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='block_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='block_3',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='exact_birth_month',
            field=models.CharField(max_length=255, null=True, verbose_name='Month of birth'),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_1',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_10',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_11',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_2',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_3',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_4',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_5',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_6',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_7',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_8',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_9',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_persons_hundreds',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_persons_ones',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_persons_tens',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('1', '1'), max_length=255, null=True, verbose_name=''),
        ),
    ]
