# Generated by Django 3.1.4 on 2021-04-19 15:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EntryApp', '0003_auto_20210413_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(max_length=255)),
                ('img_file_name', models.CharField(max_length=255)),
                ('img_folder_path', models.CharField(max_length=255)),
                ('img_reel', models.CharField(max_length=255)),
                ('img_position', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(null=True)),
                ('image_type', models.CharField(choices=[('breaker', 'Breaker'), ('sheet', 'Sheet'), ('other', 'Other')], max_length=8, null=True)),
                ('is_complete', models.BooleanField(null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('problem', models.BooleanField(default=False)),
                ('prob_description', models.TextField(null=True, verbose_name='Please describe the problem.')),
                ('flagged_view', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='image',
            name='unique_img_entry',
        ),
        migrations.AddField(
            model_name='breaker',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='breaker',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='otherimage',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherimage',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='record',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sheet',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheet',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EntryApp.imagefile'),
        ),
    ]
