# Generated by Django 3.1.4 on 2021-04-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryApp', '0004_auto_20210419_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_path',
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='img_folder_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='img_path',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('image_file', 'jbid'), name='unique_img_entry'),
        ),
    ]
