# Generated by Django 3.1.4 on 2021-04-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryApp', '0005_auto_20210420_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefile',
            old_name='img_reel',
            new_name='img_reel_label',
        ),
        migrations.AddField(
            model_name='imagefile',
            name='img_reel_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
