# Generated by Django 3.1.4 on 2021-04-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntryApp', '0007_auto_20210421_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='flagged_view',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(blank=True, choices=[('breaker', 'Breaker'), ('sheet', 'Sheet'), ('other', 'Other')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_complete',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='prob_description',
            field=models.TextField(blank=True, null=True, verbose_name='Please describe the problem.'),
        ),
        migrations.AlterField(
            model_name='image',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
