# Generated by Django 3.1.4 on 2021-05-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EntryApp', '0008_auto_20210421_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherimage',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='otherimage',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='record',
            name='row_num',
        ),
        migrations.RemoveField(
            model_name='sheet',
            name='form_type',
        ),
        migrations.AddField(
            model_name='record',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='person_no',
            field=models.PositiveIntegerField(null=True, verbose_name='Line number'),
        ),
        migrations.AlterField(
            model_name='breaker',
            name='state',
            field=models.CharField(choices=[('AL', 'AL'), ('AK', 'AK'), ('AZ', 'AZ'), ('AR', 'AR'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DE', 'DE'), ('DC', 'DC'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('IA', 'IA'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('ME', 'ME'), ('MD', 'MD'), ('MA', 'MA'), ('MI', 'MI'), ('MN', 'MN'), ('MS', 'MS'), ('MO', 'MO'), ('MT', 'MT'), ('NE', 'NE'), ('NV', 'NV'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NY', 'NY'), ('NC', 'NC'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('PR', 'PR'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WV', 'WV'), ('WI', 'WI'), ('WY', 'WY')], default=('AL', 'AL'), max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='currententry',
            name='jbid',
            field=models.CharField(default='jbid000', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_type',
            field=models.CharField(blank=True, choices=[('breaker', 'Breaker'), ('longform', '1990 Long Form'), ('sheet', 'Sheet'), ('other', 'Other')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='imagefile',
            name='image_type',
            field=models.CharField(blank=True, choices=[('breaker', 'Breaker'), ('longform', '1990 Long Form'), ('sheet', 'Sheet'), ('other', 'Other')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='age_hundreds',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='age_ones',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='age_tens',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='apt_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Apartment number'),
        ),
        migrations.AlterField(
            model_name='record',
            name='birth_year',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name='Specific year of birth'),
        ),
        migrations.AlterField(
            model_name='record',
            name='birth_year_hundreds',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='birth_year_ones',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='birth_year_tens',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='birth_year_thousands',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='block',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='block_1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='block_2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='block_3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='house_no',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='House number'),
        ),
        migrations.AlterField(
            model_name='record',
            name='ind',
            field=models.CharField(max_length=255, null=True, verbose_name='Industry'),
        ),
        migrations.AlterField(
            model_name='record',
            name='jbid',
            field=models.CharField(default='jbid000', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Separated', 'Separated'), ('Never married', 'Never married')], default=('Married', 'Married'), max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='middle_init',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='occp',
            field=models.CharField(max_length=255, null=True, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='record',
            name='race_1960',
            field=models.CharField(choices=[('White', 'White'), ('Negro', 'Negro'), ('American Indian', 'American Indian'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese'), ('Filipino', 'Filipino'), ('Other', 'Other')], default=('White', 'White'), max_length=255, null=True, verbose_name='Race'),
        ),
        migrations.AlterField(
            model_name='record',
            name='race_1970',
            field=models.CharField(choices=[('White', 'White'), ('Negro or Black', 'Negro or Black'), ('Indian (Amer.)', 'Indian (Amer.)'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese'), ('Filipino', 'Filipino'), ('Hawaiian', 'Hawaiian'), ('Korean', 'Korean'), ('Other', 'Other')], default=('White', 'White'), max_length=255, null=True, verbose_name='Race'),
        ),
        migrations.AlterField(
            model_name='record',
            name='race_1980',
            field=models.CharField(choices=[('White', 'White'), ('Black or Negro', 'Black or Negro'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese'), ('Filipino', 'Filipino'), ('Korean', 'Korean'), ('Vietnamese', 'Vietnamese'), ('Indian (Amer.)', 'Indian (Amer.)'), ('Asian Indian', 'Asian Indian'), ('Hawaiian', 'Hawaiian'), ('Guamanian', 'Guamanian'), ('Samoan', 'Samoan'), ('Eskimo', 'Eskimo'), ('Aleut', 'Aleut'), ('Other', 'Other')], default=('White', 'White'), max_length=255, null=True, verbose_name='Race'),
        ),
        migrations.AlterField(
            model_name='record',
            name='race_1990',
            field=models.CharField(choices=[('White', 'White'), ('Black or Negro', 'Black or Negro'), ('Indian (Amer.)', 'Indian (Amer.)'), ('Eskimo', 'Eskimo'), ('Aleut', 'Aleut'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Filipino', 'Filipino'), ('Asian Indian', 'Asian Indian'), ('Hawaiian', 'Hawaiian'), ('Samoan', 'Samoan'), ('Korean', 'Korean'), ('Guamanian', 'Guamanian'), ('Vietnamese', 'Vietnamese'), ('Other API', 'Other API')], default=('White', 'White'), max_length=255, null=True, verbose_name='Race'),
        ),
        migrations.AlterField(
            model_name='record',
            name='relp_1960',
            field=models.CharField(choices=[('hh_head', 'Head of household'), ('spouse', 'Wife'), ('child', 'Child'), ('other_relative', 'Other relative'), ('roomer/boarder', 'Roomer, boarder, lodger'), ('patient/inmate', 'Patient or inmate'), ('other', 'Other not related to head')], default=('hh_head', 'Head of household'), max_length=255, null=True, verbose_name='Relationship to household head'),
        ),
        migrations.AlterField(
            model_name='record',
            name='relp_1970',
            field=models.CharField(choices=[('hh_head', 'Head of household'), ('spouse', 'Wife of head'), ('child', 'Son or daughter of head'), ('other_relative', 'Other relative'), ('roomer/boarder', 'Roomer, boarder, lodger'), ('patient/inmate', 'Patient or inmate'), ('other', 'Other not related to head')], default=('hh_head', 'Head of household'), max_length=255, null=True, verbose_name='Relationship to household head'),
        ),
        migrations.AlterField(
            model_name='record',
            name='relp_1980',
            field=models.CharField(choices=[('spouse', 'Husband/wife'), ('child', 'Son/daughter'), ('sibling', 'Brother/sister'), ('parent', 'Father/mother'), ('other_relative', 'Other relative'), ('roomer/boarder', 'Roomer, boarder'), ('partner/roommate', 'Partner, roommate'), ('paid_employee', 'Paid employee'), ('other', 'Other nonrelative')], default=('spouse', 'Husband/wife'), max_length=255, null=True, verbose_name='Relationship to household head'),
        ),
        migrations.AlterField(
            model_name='record',
            name='relp_1990',
            field=models.CharField(choices=[('spouse', 'Husband/wife'), ('child', 'Son/daughter'), ('stepchild', 'Stepson/stepdaughter'), ('sibling', 'Brother/sister'), ('parent', 'Father/mother'), ('grandchild', 'Grandchild'), ('other_relative', 'Other relative'), ('roomer/boarder/foster', 'Roomer, boarder, or foster child'), ('housemate/roommate', 'Housemate, roommate'), ('unmarried_partner', 'Unmarried partner'), ('other', 'Other nonrelative')], default=('spouse', 'Husband/wife'), max_length=255, null=True, verbose_name='Relationship to household head'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sample_key_gq',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('GQ', 'GQ')], default=('A', 'A'), max_length=255, null=True, verbose_name='Sample key'),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_1',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_10',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_11',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_2',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_3',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_4',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_5',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_6',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_7',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_8',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='serial_no_9',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=('male', 'Male'), max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_persons_hundreds',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_persons_ones',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='total_persons_tens',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=('0', '0'), max_length=255, null=True, verbose_name=''),
        ),
        migrations.CreateModel(
            name='LongForm1990',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jbid', models.CharField(default='jbid000', max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('serial_no', models.IntegerField(null=True, verbose_name='Household serial number')),
                ('person_no', models.PositiveIntegerField(null=True, verbose_name='Person number')),
                ('employer', models.CharField(max_length=255, null=True, verbose_name='28a. Name of company, business, or other employer')),
                ('industry', models.CharField(max_length=255, null=True, verbose_name='28b. What kind of business or industry was this?')),
                ('industry_category', models.CharField(choices=[('Manufacturing', 'Manufacturing'), ('Wholesale trade', 'Wholesale trade'), ('Retail trade', 'Retail trade'), ('Other (agriculture, construction, service, government, etc.)', 'Other (agriculture, construction, service, government, etc.)')], default=('Manufacturing', 'Manufacturing'), max_length=255, null=True, verbose_name=' 28c. Is this business mainly - Fill ONE circle')),
                ('occupation', models.CharField(max_length=255, null=True, verbose_name='29a. What kind of work was this person doing?')),
                ('occupation_detail', models.CharField(max_length=255, null=True, verbose_name="29b. What were this person's most important activities or duties?")),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EntryApp.image')),
            ],
        ),
        migrations.AddConstraint(
            model_name='longform1990',
            constraint=models.UniqueConstraint(fields=('img', 'jbid'), name='unique_1990LF_entry'),
        ),
    ]
